import Head from "next/head";
import EventList from "../components/events/event-list";
import styles from "../styles/Home.module.css";
import { getFeaturedEvents } from "./../dummy-data";

export default function Home() {
  const featuredEvents = getFeaturedEvents();
  // console.log(featuredEvents);

  return (
    <div className={styles.container}>
      <Head>
        <title>Next JS Learning</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <EventList items={featuredEvents}></EventList>
    </div>
  );
}
